### DISCUSSION TITLE
Setup SQLite on Fly

### DISCUSSION THREAD

**Discussion by ndrean** [dwyl/PWA-Liveview#52] [General]
## CLI commands

```
> fly launch --no-deploy
```

‼️ Then reset the "fly.toml" as below because Fly modified the settings. HARD to find...!

```toml
# [deploy]
#   release_command = '/app/bin/migrate'

[[mounts]]
source = 'db'
destination = '/data'
auto_extend_size_threshold = 80
auto_extend_size_increment = '1GB'
auto_extend_size_limit = '1GB'
```

Then:
```
> fly volumes create db --size 1 --region xxx
> fly deploy
```

```
Creating a 1 GB volume named 'db' for process group 'app'.
```

## Migrations are run by Elixir,  in the Application.ex module

```elixir
def Application do

  def start(_) dà
     LiveviewPwa.Release.migrate()
     [...]
  end
end
```
