### ISSUE TITLE
Error on volumes

### ISSUE THREAD

**Issue by ndrean** [dwyl/PWA-Liveview#10]
Counter is persisted (?) and broadcasted. 
```toml
[env]
DATABASE_PATH = '/mnt/db/airports.db'
PHX_HOST = 'solidyjs-lively-pine-4375.fly.dev'
PORT = '8080'
MIX_ENV = 'prod'

[[mounts]]
source = 'db'
destination = '/mnt/db'
```

=>
```txt
Error: machine 080ee20a06d368 [app] can't update the attached volume db with name 'vol_vw2qgxgopxq7zxmv' by 'name'
```

**Comment by ndrean** [comment]
Works (counter persistence, broadcasting and SQLite database) with settings: 

```toml
[env]
DATABASE_PATH = '/mnt/db/airports.db'
MIX_ENV = 'prod'
PHX_HOST = 'solidyjs-lively-pine-4375.fly.dev'
PORT = '8080'

[[mounts]]
source = 'name'
destination = '/mnt/db'
....
```
